### ISSUE TITLE
Create test fixtures for `yapapi.Golem`

### ISSUE THREAD

**Issue by approxit** [golemfactory/dapp-runner#79]
# Background
While making #76 we've encountered problem with mocking out `yapapi.Golem` in unit tests for `runner.Runner`. `runner.Runner` is so much entangled with `yapapi.Golem`, that simple `unittests.Mock` is not enough to get it working. Shortcut solution was chosen then, but now, we need something more mature.

# Goal
We need `yapapi.Golem` fixture that can be used to unit test `runner.Runner`. Bare minimum is required to just start `runner.Runner` even with empty dapp without errors, also we need to manipulate nodes states to properly setup app state tests.

# Definition of done
- [x] `runner.Runner` instance is working at level of unit tests with mocked out `yapapi.Golem`
- [x] Previous shortcuts are refactored:
- - [x]  [static method on app state](https://github.com/golemfactory/dapp-runner/pull/78/files#diff-7e95d1df54a34e8fcdfa411dd083e84d5248ac5caf649d19bd03f4842c697188R280)
- - [x] [skipped tests](https://github.com/golemfactory/dapp-runner/pull/78/files#diff-2e3636870703a1536c75f73f75b914316dd333c307cffddd1e8a5e2927327a7fR83)

**Comment by mateuszsrebrny** [comment]
@shadeofblue should have a look, diagnose and then explain to @approxit & @lucekdudek how the diagnosing went on.
